services:
  test-automation-practicing:
    image: training360/test-automation-practicing:1.0.0
    container_name: test-automation-practicing
    ports:
      - "80:80"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
